### ISSUE TITLE
Inaccurate Authenticode hash calculations

### ISSUE THREAD

**Issue by HotCakeX** [hfiref0x/AuthHashCalc#6]
Hi,
The Authenticode hashes are not calculated properly for all files. For example, I found this file where AuthHashCalc calculates the wrong hashes but [my module](https://github.com/HotCakeX/Harden-Windows-Security/wiki/Get-CiFileHashes) calculates the right ones. The reason I know this is because I scanned the file with the built-in ConfigCI cmdlets to generate a WDAC policy using Hash level and there I can see the correct Authenticode and Page hashes of the file. 

[cmdlet code](https://github.com/HotCakeX/Harden-Windows-Security/blob/main/WDACConfig/WDACConfig%20Module%20Files/Core/Get-CiFileHashes.psm1)

<img width="971" alt="image" src="https://github.com/hfiref0x/AuthHashCalc/assets/118815227/e0c338d7-628b-4391-b4d7-26585e36ebc4">

<br>

<br>

<img width="1208" alt="image" src="https://github.com/hfiref0x/AuthHashCalc/assets/118815227/bf85f03a-84af-49d8-8c21-9a93e0783b44">

**Comment by hfiref0x** [comment]
Hello,

Where is this file can be downloaded?

**Comment by HotCakeX** [comment]
@hfiref0x 

I put it in this zip

[ShadowExplorer-0.9-setup.exe.zip](https://github.com/hfiref0x/AuthHashCalc/files/14366261/ShadowExplorer-0.9-setup.exe.zip)

**Comment by hfiref0x** [comment]
Your report is valid.

Microsoft calculates authenticode for file with padding added to the end of file if necessary. 

In this particular file case since there is an overlay with odd size present it fired up such situation.

Which mean entire VirusTotal/Sysinformer and several other tools/services calculates authenticode in a wrong way too.

**Comment by HotCakeX** [comment]
Thanks for the explanation, what if you used wintrust.dll for hash calculations? This way if MS changes hashing algorithms (by adding SHA3 support and so on) or the way some file hashes are calculated, your tool will also automatically be compatible.

There are files that can't even be hashed like the uninstall.exe in OBS software, for those files the flat hashes are calculated in WDAC policies.

**Comment by hfiref0x** [comment]
I cannot use all the fancy new Windows API because I need this to be working on machines with Windows versions that MS officially dropped. If MS will introduce new hashing algo then I will add it.

I've prepared preliminary fix for issue, can you check it out?

As of OBS uninstaller I can tell that this particular file contain corrupted PE structure. It doesn't affect Windows loader however as it doesn't do deep and all-kind-of file structure validation because of multiple reasons. 

Probably this is result of NSIS developer mad skills. NSIS is ancient installation system that should not be used at all in 2024 as it seems produce the inaccurate PE binaries.

![OBS](https://github.com/hfiref0x/AuthHashCalc/assets/10708977/45f699c7-8607-481d-9cd1-03292e411efb)

**Comment by HotCakeX** [comment]
Thanks, the hashes are accurate now ^^
I don't have a way to verify SHA2-384 and 512 hashes yet though,

I wonder, why Virus total and others were affected, they weren't all using your tool, were they ?

Oh I'm surprised a popular software such as OBS uses those old stuff

**Comment by hfiref0x** [comment]
Well, this is Microsoft creation. Anything good they always keep closed (except this https://download.microsoft.com/download/9/c/5/9c5b2167-8017-4bae-9fde-d599bac8184a/Authenticode_PE.docx). Overall authenticode calculation algorithm is known and mostly rely on primitive PE format parsing plus using widely known hashing algorithms for actual signature calculation. Since it is nowhere clearly specified everybody understands it as they could.
